import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { checked, rejected, runGo, command } from './support.mjs';

const program = body => `fn main(): Int = ${body};`;

test('example runs through PureScript CLI, Go build, and executable', () => {
  assert.equal(command('node', ['scripts/sprig.mjs', 'run', 'examples/answer.sprig']), '42\n');
});

test('CLI emit and build are concrete artifacts', () => {
  const work = mkdtempSync(join(tmpdir(), 'sprig-cli-'));
  try {
    const go = join(work, 'main.go');
    const binary = join(work, 'answer');
    command('node', ['scripts/sprig.mjs', 'emit', 'examples/answer.sprig', go]);
    assert.equal(readFileSync(go, 'utf8'), checked(readFileSync('examples/answer.sprig', 'utf8')));
    command('node', ['scripts/sprig.mjs', 'build', 'examples/answer.sprig', binary]);
    assert.equal(command(binary, []), '42\n');
  } finally { rmSync(work, { recursive: true, force: true }); }
});

test('negative fixtures have exact structured source diagnostics', () => {
  for (const [fixture, code, column, width] of [
    ['syntax', 'E_SYNTAX', 18, 1], ['unbound', 'E_UNBOUND', 18, 7], ['type', 'E_TYPE', 18, 4]
  ]) {
    const file = `negative/${fixture}.sprig`;
    const source = readFileSync(file, 'utf8');
    const diagnostic = rejected(source, code);
    assert.deepEqual(diagnostic.span, {
      start: { offset: 17, line: 1, column },
      end: { offset: 17 + width, line: 1, column: column + width }
    });
    const result = spawnSync('node', ['scripts/sprig.mjs', 'emit', file, '.build/rejected.go'], { encoding: 'utf8' });
    assert.equal(result.status, 1);
    const wire = JSON.parse(result.stderr);
    assert.equal(wire.code, code);
    assert.equal(wire.file, file);
    assert.deepEqual(wire.span, diagnostic.span);
    assert.equal(existsSync('.build/rejected.go'), false);
  }
});

test('all expected semantic and boundary refusals have tags', () => {
  for (const [source, code] of [
    [program('-true'), 'E_SYNTAX'], [program('--1'), 'E_SYNTAX'], [program('@'), 'E_LEX'], [program('2147483648'), 'E_INTEGER'],
    [program('-2147483649'), 'E_INTEGER'], [program('true + 1'), 'E_TYPE'],
    [program('if 1 then 2 else 3'), 'E_TYPE'], [program('if true then 1 else false'), 'E_TYPE'],
    [program('missing()'), 'E_UNBOUND'], ['fn x(): Int = 1;', 'E_ENTRY'],
    ['fn main(x: Int): Int = x;', 'E_ENTRY'],
    ['fn main(): Int = 1; fn main(): Int = 2;', 'E_DUPLICATE'],
    ['fn f(x: Int, x: Bool): Int = 1; fn main(): Int = 0;', 'E_DUPLICATE'],
    ['fn f(x: Int): Int = x; fn main(): Int = f();', 'E_ARITY'],
    ['fn f(x: Int): Int = x; fn main(): Int = f(false);', 'E_TYPE'],
    ['fn f(x: Int): Int = x(); fn main(): Int = 0;', 'E_NOT_CALLABLE'],
    [program('1') + 'garbage', 'E_SYNTAX'], [program('1.0'), 'E_LEX'],
    ['fn main(): Int = 1', 'E_SYNTAX'], ['fn main(): Int = 1 + ;', 'E_SYNTAX'],
    ['fn main(): Int = if true then 1;', 'E_SYNTAX'],
    ['fn main(): Float = 1;', 'E_SYNTAX'],
    ['fn unused(): Int = false; fn main(): Int = 1;', 'E_TYPE']
  ]) rejected(source, code);
});

test('integer literals and addition are signed 32-bit, including constant overflow', () => {
  assert.equal(runGo(program('2147483647 + 1')), '-2147483648\n');
  assert.equal(runGo(program('-2147483648 + -1')), '2147483647\n');
  assert.equal(runGo(program('00042')), '42\n');
});

test('conditionals evaluate only the selected branch; unused parameters are legal', () => {
  const source = 'fn loop(): Int = loop(); fn choose(unused: Int): Int = if false then loop() else 42; fn main(): Int = choose(0);';
  assert.equal(runGo(source), '42\n');
});

test('forward calls, local shadowing, Go keywords, and Bool results', () => {
  assert.equal(runGo('fn main(): Bool = package(false); fn package(sprigAdd: Bool): Bool = if sprigAdd then false else true;'), 'true\n');
  assert.equal(runGo('fn main(): Int = f(42); fn f(f: Int): Int = f;'), '42\n');
});

test('generated bytes agree across CLI invocations and bootstrap snapshot', () => {
  assert.equal(checked(readFileSync('examples/answer.sprig', 'utf8')), readFileSync('bootstrap/answer.go', 'utf8'));
});

test('EOF and multiline diagnostic positions are exact', () => {
  const source = 'fn main(): Int =\n  true;';
  assert.deepEqual(rejected(source, 'E_TYPE').span.start, { offset: 19, line: 2, column: 3 });
  const eof = rejected('fn main(): Int = 1\n', 'E_SYNTAX');
  assert.deepEqual(eof.span, { start: { offset: 19, line: 2, column: 1 }, end: { offset: 19, line: 2, column: 1 } });
});
