module Format.Go (emit) where

import Prelude
import Data.Array as Array
import Data.String.Common (joinWith)
import Domain.IR.Internal as IR
import Format.Go.Cleanup (cleanupRuntime, guardedMain)
import Format.Go.Compare (boolHelper, compareHelpers)
import Format.Go.Context (declared, runtime)
import Format.Go.Data
  ( declarations
  , funTypeDeclarations
  , functionName
  , goType
  , localName
  )
import Format.Go.Effect (effectDeclarations)
import Format.Go.Expression (expression)
import Format.Go.Layout (Layout, layout)
import Format.Go.Lowered (Shape, Wrapper, shapeOf)
import Format.Go.Show (appendsWithFmt, printed, showHelpers)
import Format.Go.Stage (staged)
import Format.Go.Usage (needsBoolHelper, needsPrint)
import Domain.IR.Internal (Ty(..))
import Domain.Resolved (FunctionId, LocalId(..))

-- One function's Go, its lifted functions included, and the staged
-- wrappers its values need.
type Emitted = { code ∷ String, wrappers ∷ Array Wrapper }

-- A program with no function value has no wrapper, so it emits no node
-- type and no stage (design §13 rule 1): its Go is unchanged. fmt is
-- imported when main prints or a printer appends with it; a program whose
-- main returns Unit and holds no Int or Bool field uses neither (FX001).
emit ∷ IR.Program → String
emit program'@(IR.Program program) =
  "// Code generated by Waxwing stage 0. DO NOT EDIT.\n"
    <> "package main\n\n"
    <> imports usesFmt shape.defects
    <> "func waxwingAdd(a int32, b int32) int32 { return a + b }\n\n"
    <> (if needsBoolHelper program' then boolHelper else "")
    <>
      ( if shape.context then runtime <> effectDeclarations program.effects
        else ""
      )
    <> (if shape.defects then cleanupRuntime shape.context else "")
    <> declarations shape.context tables
    <> funTypeDeclarations shape.context program.funTypes
    <> stages.nodes
    <> compareHelpers tables
    <> showHelpers tables
    <> joinWith "\n" (map codeOf functions)
    <> stages.code
    <> joinWith ""
      (map (entryMain shape program.entry) program.functions)
  where
  -- Computed once; every emitter reads it instead of searching (I3).
  tables = layout { types: program.types, ctors: program.ctors }
  shape = shapeOf program'
  functions = map (function tables shape) program.functions
  stages = staged shape (Array.concatMap wrappersOf functions)
  usesFmt = needsPrint program'
    || shape.defects
    || Array.any (printing program.entry) program.functions
    || appendsWithFmt tables
  codeOf emitted = emitted.code
  wrappersOf emitted = emitted.wrappers

-- Exactly one function is the entry (Features.Resolve); scanning the
-- definitions finds its result type without a lookup that could fail.
-- A Unit result prints nothing at all (FX001 design §1, Entry).
entryMain ∷ Shape → FunctionId → IR.FunctionDecl → String
entryMain shape entry definition
  | definition.id /= entry = ""
  | definition.result == TUnit = "\nfunc main() { "
      <> guardedMain shape.defects (entered shape.context entry)
      <> " }\n"
  | otherwise = "\nfunc main() { "
      <> guardedMain shape.defects
        ( "fmt.Println("
            <> printed definition.result (entered shape.context entry)
            <> ")"
        )
      <> " }\n"

-- fmt, and os for the defect report, as the program needs them; a program
-- with neither emits no import.
imports ∷ Boolean → Boolean → String
imports fmt os
  | fmt && os = "import (\n\t\"fmt\"\n\t\"os\"\n)\n\n"
  | fmt = "import \"fmt\"\n\n"
  | otherwise = ""

-- The entry runs under no handler: an empty context.
entered ∷ Boolean → FunctionId → String
entered context entry = functionName entry
  <> (if context then "(nil)" else "()")

printing ∷ FunctionId → IR.FunctionDecl → Boolean
printing entry definition = definition.id == entry
  && definition.result /= TUnit

-- Each function is followed by the functions its matches, lambdas, pipes
-- and application helpers were lifted to, in number order.
function ∷ Layout → Shape → IR.FunctionDecl → Emitted
function tables shape definition =
  { code: "func " <> functionName definition.id <> "("
      <> joinWith ", " (declared shape.context parameters)
      <> ") "
      <> goType definition.result
      <> " {\nreturn "
      <> body.code
      <> "\n}\n"
      <> joinWith "" (map separated body.lifted)
  , wrappers: body.wrappers
  }
  where
  body = expression { tables, owner: definition.id, shape } 0 definition.body
  parameters = Array.mapWithIndex parameter definition.parameters
  parameter index ty = localName (LocalId index) <> " " <> goType ty
  separated lifted = "\n" <> lifted
