// Code generated by Bumpus stage 0. DO NOT EDIT.
package main

import "fmt"

func bumpusAdd(a int32, b int32) int32 { return a + b }

func bumpusFn0(bumpusLocal0 int32, bumpusLocal1 int32) int32 {
return bumpusAdd(bumpusLocal0, bumpusLocal1)
}

func bumpusFn1(bumpusLocal0 bool, bumpusLocal1 int32, bumpusLocal2 int32) int32 {
return func() int32 { if bumpusLocal0 { return bumpusLocal1 }; return bumpusLocal2 }()
}

func bumpusFn2() int32 {
return bumpusFn1(true, bumpusFn0(int32(20), int32(22)), int32(0))
}

func main() { fmt.Println(bumpusFn2()) }
