// Code generated by Waxwing stage 0. DO NOT EDIT.
package main

import "fmt"

func waxwingAdd(a int32, b int32) int32 { return a + b }

func waxwingFn0(waxwingLocal0 int32, waxwingLocal1 int32) int32 {
return waxwingAdd(waxwingLocal0, waxwingLocal1)
}

func waxwingFn1(waxwingLocal0 bool, waxwingLocal1 int32, waxwingLocal2 int32) int32 {
return func() int32 { if waxwingLocal0 { return waxwingLocal1 }; return waxwingLocal2 }()
}

func waxwingFn2() int32 {
return waxwingFn1(true, waxwingFn0(int32(20), int32(22)), int32(0))
}

func main() { fmt.Println(waxwingFn2()) }
