// Code generated by Sprig stage 0. DO NOT EDIT.
package main

import "fmt"

func sprigAdd(a int32, b int32) int32 { return a + b }

func sprigFn0(sprigLocal0 int32, sprigLocal1 int32) int32 {
return sprigAdd(sprigLocal0, sprigLocal1)
}

func sprigFn1(sprigLocal0 bool, sprigLocal1 int32, sprigLocal2 int32) int32 {
return func() int32 { if sprigLocal0 { return sprigLocal1 }; return sprigLocal2 }()
}

func sprigFn2() int32 {
return sprigFn1(true, sprigFn0(int32(20), int32(22)), int32(0))
}

func main() { fmt.Println(sprigFn2()) }
