// Code generated by Bumpus stage 0. DO NOT EDIT.
package main

import "fmt"

func bumpusAdd(a int32, b int32) int32 { return a + b }

type bumpusTy0 struct {
tag uint32
c1f0 int32
c1f1 *bumpusTy0
}

func bumpusCtor0() bumpusTy0 { return bumpusTy0{tag: 1} }

func bumpusCtor1(f0 int32, f1 bumpusTy0) bumpusTy0 { return bumpusTy0{tag: 2, c1f0: f0, c1f1: &f1} }

type bumpusTy1 struct {
tag uint32
c2f0 int32
c2f1 *bumpusTy0
}

func bumpusCtor2(f0 int32, f1 bumpusTy0) bumpusTy1 { return bumpusTy1{tag: 1, c2f0: f0, c2f1: &f1} }

type bumpusFun0 func(bumpusTy0) bumpusTy0

type bumpusFun1 func(int32) bool

type bumpusFun2 func(int32) int32

type bumpusFun3 func(bumpusTy0) int32

type bumpusFun4 func(int32) bumpusFun2

type bumpusNode0 struct { value int32; previous any }

type bumpusNode1 struct { value bumpusFun2; previous any }

func bumpusCmp0(a bumpusTy0, b bumpusTy0) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 < b.c1f0 { return -1 }; if a.c1f0 > b.c1f0 { return 1 }
if a.c1f1 == nil || b.c1f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c1f1, *b.c1f1); c != 0 { return c }
}
return 0
}

func bumpusCmp1(a bumpusTy1, b bumpusTy1) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c2f0 < b.c2f0 { return -1 }; if a.c2f0 > b.c2f0 { return 1 }
if a.c2f1 == nil || b.c2f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func bumpusShow0(out []byte, v bumpusTy0) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
out = fmt.Append(out, v.c1f0)
out = append(out, ", "...)
if v.c1f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c1f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow1(out []byte, v bumpusTy1) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
out = fmt.Append(out, v.c2f0)
out = append(out, ", "...)
if v.c2f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c2f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusFn0(bumpusLocal0 int32, bumpusLocal1 int32) int32 {
return bumpusAdd(bumpusLocal0, bumpusLocal1)
}

func bumpusFn1(bumpusLocal0 int32) int32 {
return bumpusAdd(bumpusLocal0, bumpusLocal0)
}

func bumpusFn2(bumpusLocal0 int32) bumpusTy0 {
return func() bumpusTy0 { if (bumpusLocal0 <= int32(0)) { return bumpusCtor0() }; return bumpusCtor1(bumpusLocal0, bumpusFn2(bumpusAdd(bumpusLocal0, int32(-1)))) }()
}

func bumpusFn3() bumpusTy1 {
return bumpusCtor2(bumpusFn3Pipe0(bumpusFn3Pipe1(bumpusFn3Pipe2(bumpusFn2(int32(5))))), bumpusFn5(bumpusFn0Value(int32(100)), bumpusCtor1(int32(1), bumpusCtor1(int32(2), bumpusCtor0()))))
}

func bumpusFn3Pipe0(bumpusPipe bumpusTy0) int32 {
return bumpusFn7(bumpusFn0Value, int32(0), bumpusPipe)
}

func bumpusFn3Pipe1(bumpusPipe bumpusTy0) bumpusTy0 {
return bumpusFn5(bumpusFn6(bumpusFn0Value(int32(1)), bumpusFn1), bumpusPipe)
}

func bumpusFn3Pipe2(bumpusPipe bumpusTy0) bumpusTy0 {
return bumpusFn4(bumpusFn3Lambda3, bumpusPipe)
}

func bumpusFn3Lambda3(bumpusLocal0 int32) bool {
return (bumpusLocal0 > int32(2))
}

func bumpusFn4(bumpusLocal0 bumpusFun1, bumpusLocal1 bumpusTy0) bumpusTy0 {
return bumpusFn4Match0(bumpusLocal0, bumpusLocal1)
}

func bumpusFn4Match0(bumpusLocal0 bumpusFun1, bumpusScrutinee bumpusTy0) bumpusTy0 {
if bumpusScrutinee.tag == 1 { return bumpusCtor0() }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c1f1 != nil {
bumpusLocal2 := bumpusScrutinee.c1f0
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c1f1
_ = bumpusLocal3
return func() bumpusTy0 { if bumpusLocal0(bumpusLocal2) { return bumpusCtor1(bumpusLocal2, bumpusFn4(bumpusLocal0, bumpusLocal3)) }; return bumpusFn4(bumpusLocal0, bumpusLocal3) }()
}
panic("bumpus: unmatched value")
}

func bumpusFn5(bumpusLocal0 bumpusFun2, bumpusLocal1 bumpusTy0) bumpusTy0 {
return bumpusFn5Match0(bumpusLocal0, bumpusLocal1)
}

func bumpusFn5Match0(bumpusLocal0 bumpusFun2, bumpusScrutinee bumpusTy0) bumpusTy0 {
if bumpusScrutinee.tag == 1 { return bumpusCtor0() }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c1f1 != nil {
bumpusLocal2 := bumpusScrutinee.c1f0
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c1f1
_ = bumpusLocal3
return bumpusCtor1(bumpusLocal0(bumpusLocal2), bumpusFn5(bumpusLocal0, bumpusLocal3))
}
panic("bumpus: unmatched value")
}

func bumpusFn6(bumpusLocal0 bumpusFun2, bumpusLocal1 bumpusFun2) bumpusFun2 {
return bumpusFn6Lambda0Value(bumpusLocal0)(bumpusLocal1)
}

func bumpusFn6Lambda0(bumpusLocal0 bumpusFun2, bumpusLocal1 bumpusFun2, bumpusLocal2 int32) int32 {
return bumpusLocal0(bumpusLocal1(bumpusLocal2))
}

func bumpusFn7(bumpusLocal0 bumpusFun4, bumpusLocal1 int32, bumpusLocal2 bumpusTy0) int32 {
return bumpusFn7Match0(bumpusLocal0, bumpusLocal1, bumpusLocal2)
}

func bumpusFn7Match0(bumpusLocal0 bumpusFun4, bumpusLocal1 int32, bumpusScrutinee bumpusTy0) int32 {
if bumpusScrutinee.tag == 1 { return bumpusLocal1 }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c1f1 != nil {
bumpusLocal3 := bumpusScrutinee.c1f0
_ = bumpusLocal3
bumpusLocal4 := *bumpusScrutinee.c1f1
_ = bumpusLocal4
return bumpusFn7(bumpusLocal0, bumpusLocal0(bumpusLocal1)(bumpusLocal3), bumpusLocal4)
}
panic("bumpus: unmatched value")
}

func bumpusFn0Value(x int32) bumpusFun2 { return bumpusFn0Stage2(&bumpusNode0{x, nil}) }

func bumpusFn0Stage2(e any) bumpusFun2 { return func(x int32) int32 { return bumpusFn0Entry(&bumpusNode0{x, e}) } }

var bumpusFn0Kinds = [2]int32{0, 0}

var bumpusFn0Slots = [2]int32{0, 1}

func bumpusFn0Entry(e any) int32 {
var a0 [2]int32
for p := 1; p >= 0; p-- {
switch bumpusFn0Kinds[p] {
case 0:
v := e.(*bumpusNode0)
a0[bumpusFn0Slots[p]] = v.value
e = v.previous
}
}
return bumpusFn0(a0[0], a0[1])
}

type bumpusFn6Lambda0Arrow1 func(bumpusFun2) bumpusFn6Lambda0Arrow2

type bumpusFn6Lambda0Arrow2 func(bumpusFun2) bumpusFun2

func bumpusFn6Lambda0Value(x bumpusFun2) bumpusFn6Lambda0Arrow2 { return bumpusFn6Lambda0Stage2(&bumpusNode1{x, nil}) }

func bumpusFn6Lambda0Stage2(e any) bumpusFn6Lambda0Arrow2 { return func(x bumpusFun2) bumpusFun2 { return bumpusFn6Lambda0Stage3(&bumpusNode1{x, e}) } }

func bumpusFn6Lambda0Stage3(e any) bumpusFun2 { return func(x int32) int32 { return bumpusFn6Lambda0Entry(&bumpusNode0{x, e}) } }

var bumpusFn6Lambda0Kinds = [3]int32{0, 0, 1}

var bumpusFn6Lambda0Slots = [3]int32{0, 1, 0}

func bumpusFn6Lambda0Entry(e any) int32 {
var a0 [2]bumpusFun2
var a1 [1]int32
for p := 2; p >= 0; p-- {
switch bumpusFn6Lambda0Kinds[p] {
case 0:
v := e.(*bumpusNode1)
a0[bumpusFn6Lambda0Slots[p]] = v.value
e = v.previous
case 1:
v := e.(*bumpusNode0)
a1[bumpusFn6Lambda0Slots[p]] = v.value
e = v.previous
}
}
return bumpusFn6Lambda0(a0[0], a0[1], a1[0])
}

func main() { fmt.Println(string(bumpusShow1(nil, bumpusFn3()))) }
