// Code generated by Waxwing stage 0. DO NOT EDIT.
package main

import "fmt"

func waxwingAdd(a int32, b int32) int32 { return a + b }

type waxwingTy0 struct {
tag uint32
c1f0 int32
c1f1 *waxwingTy0
}

func waxwingCtor0() waxwingTy0 { return waxwingTy0{tag: 1} }

func waxwingCtor1(f0 int32, f1 waxwingTy0) waxwingTy0 { return waxwingTy0{tag: 2, c1f0: f0, c1f1: &f1} }

type waxwingTy1 struct {
tag uint32
c2f0 int32
c2f1 *waxwingTy0
}

func waxwingCtor2(f0 int32, f1 waxwingTy0) waxwingTy1 { return waxwingTy1{tag: 1, c2f0: f0, c2f1: &f1} }

type waxwingFun0 func(waxwingTy0) waxwingTy0

type waxwingFun1 func(int32) bool

type waxwingFun2 func(int32) int32

type waxwingFun3 func(waxwingTy0) int32

type waxwingFun4 func(int32) waxwingFun2

type waxwingNode0 struct { value int32; previous any }

type waxwingNode1 struct { value waxwingFun2; previous any }

func waxwingCmp0(a waxwingTy0, b waxwingTy0) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 < b.c1f0 { return -1 }; if a.c1f0 > b.c1f0 { return 1 }
if a.c1f1 == nil || b.c1f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c1f1, *b.c1f1); c != 0 { return c }
}
return 0
}

func waxwingCmp1(a waxwingTy1, b waxwingTy1) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c2f0 < b.c2f0 { return -1 }; if a.c2f0 > b.c2f0 { return 1 }
if a.c2f1 == nil || b.c2f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func waxwingShow0(out []byte, v waxwingTy0) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
out = fmt.Append(out, v.c1f0)
out = append(out, ", "...)
if v.c1f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c1f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow1(out []byte, v waxwingTy1) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
out = fmt.Append(out, v.c2f0)
out = append(out, ", "...)
if v.c2f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c2f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingFn0(waxwingLocal0 int32, waxwingLocal1 int32) int32 {
return waxwingAdd(waxwingLocal0, waxwingLocal1)
}

func waxwingFn1(waxwingLocal0 int32) int32 {
return waxwingAdd(waxwingLocal0, waxwingLocal0)
}

func waxwingFn2(waxwingLocal0 int32) waxwingTy0 {
return func() waxwingTy0 { if (waxwingLocal0 <= int32(0)) { return waxwingCtor0() }; return waxwingCtor1(waxwingLocal0, waxwingFn2(waxwingAdd(waxwingLocal0, int32(-1)))) }()
}

func waxwingFn3() waxwingTy1 {
return waxwingCtor2(waxwingFn3Pipe0(waxwingFn3Pipe1(waxwingFn3Pipe2(waxwingFn2(int32(5))))), waxwingFn5(waxwingFn0Value(int32(100)), waxwingCtor1(int32(1), waxwingCtor1(int32(2), waxwingCtor0()))))
}

func waxwingFn3Pipe0(waxwingPipe waxwingTy0) int32 {
return waxwingFn7(waxwingFn0Value, int32(0), waxwingPipe)
}

func waxwingFn3Pipe1(waxwingPipe waxwingTy0) waxwingTy0 {
return waxwingFn5(waxwingFn6(waxwingFn0Value(int32(1)), waxwingFn1), waxwingPipe)
}

func waxwingFn3Pipe2(waxwingPipe waxwingTy0) waxwingTy0 {
return waxwingFn4(waxwingFn3Lambda3, waxwingPipe)
}

func waxwingFn3Lambda3(waxwingLocal0 int32) bool {
return (waxwingLocal0 > int32(2))
}

func waxwingFn4(waxwingLocal0 waxwingFun1, waxwingLocal1 waxwingTy0) waxwingTy0 {
return waxwingFn4Match0(waxwingLocal0, waxwingLocal1)
}

func waxwingFn4Match0(waxwingLocal0 waxwingFun1, waxwingScrutinee waxwingTy0) waxwingTy0 {
if waxwingScrutinee.tag == 1 { return waxwingCtor0() }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c1f1 != nil {
waxwingLocal2 := waxwingScrutinee.c1f0
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c1f1
_ = waxwingLocal3
return func() waxwingTy0 { if waxwingLocal0(waxwingLocal2) { return waxwingCtor1(waxwingLocal2, waxwingFn4(waxwingLocal0, waxwingLocal3)) }; return waxwingFn4(waxwingLocal0, waxwingLocal3) }()
}
panic("waxwing: unmatched value")
}

func waxwingFn5(waxwingLocal0 waxwingFun2, waxwingLocal1 waxwingTy0) waxwingTy0 {
return waxwingFn5Match0(waxwingLocal0, waxwingLocal1)
}

func waxwingFn5Match0(waxwingLocal0 waxwingFun2, waxwingScrutinee waxwingTy0) waxwingTy0 {
if waxwingScrutinee.tag == 1 { return waxwingCtor0() }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c1f1 != nil {
waxwingLocal2 := waxwingScrutinee.c1f0
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c1f1
_ = waxwingLocal3
return waxwingCtor1(waxwingLocal0(waxwingLocal2), waxwingFn5(waxwingLocal0, waxwingLocal3))
}
panic("waxwing: unmatched value")
}

func waxwingFn6(waxwingLocal0 waxwingFun2, waxwingLocal1 waxwingFun2) waxwingFun2 {
return waxwingFn6Lambda0Value(waxwingLocal0)(waxwingLocal1)
}

func waxwingFn6Lambda0(waxwingLocal0 waxwingFun2, waxwingLocal1 waxwingFun2, waxwingLocal2 int32) int32 {
return waxwingLocal0(waxwingLocal1(waxwingLocal2))
}

func waxwingFn7(waxwingLocal0 waxwingFun4, waxwingLocal1 int32, waxwingLocal2 waxwingTy0) int32 {
return waxwingFn7Match0(waxwingLocal0, waxwingLocal1, waxwingLocal2)
}

func waxwingFn7Match0(waxwingLocal0 waxwingFun4, waxwingLocal1 int32, waxwingScrutinee waxwingTy0) int32 {
if waxwingScrutinee.tag == 1 { return waxwingLocal1 }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c1f1 != nil {
waxwingLocal3 := waxwingScrutinee.c1f0
_ = waxwingLocal3
waxwingLocal4 := *waxwingScrutinee.c1f1
_ = waxwingLocal4
return waxwingFn7(waxwingLocal0, waxwingLocal0(waxwingLocal1)(waxwingLocal3), waxwingLocal4)
}
panic("waxwing: unmatched value")
}

func waxwingFn0Value(x int32) waxwingFun2 { return waxwingFn0Stage2(&waxwingNode0{x, nil}) }

func waxwingFn0Stage2(e any) waxwingFun2 { return func(x int32) int32 { return waxwingFn0Entry(&waxwingNode0{x, e}) } }

var waxwingFn0Kinds = [2]int32{0, 0}

var waxwingFn0Slots = [2]int32{0, 1}

func waxwingFn0Entry(e any) int32 {
var a0 [2]int32
for p := 1; p >= 0; p-- {
switch waxwingFn0Kinds[p] {
case 0:
v := e.(*waxwingNode0)
a0[waxwingFn0Slots[p]] = v.value
e = v.previous
}
}
return waxwingFn0(a0[0], a0[1])
}

type waxwingFn6Lambda0Arrow2 func(waxwingFun2) waxwingFun2

func waxwingFn6Lambda0Value(x waxwingFun2) waxwingFn6Lambda0Arrow2 { return waxwingFn6Lambda0Stage2(&waxwingNode1{x, nil}) }

func waxwingFn6Lambda0Stage2(e any) waxwingFn6Lambda0Arrow2 { return func(x waxwingFun2) waxwingFun2 { return waxwingFn6Lambda0Stage3(&waxwingNode1{x, e}) } }

func waxwingFn6Lambda0Stage3(e any) waxwingFun2 { return func(x int32) int32 { return waxwingFn6Lambda0Entry(&waxwingNode0{x, e}) } }

var waxwingFn6Lambda0Kinds = [3]int32{0, 0, 1}

var waxwingFn6Lambda0Slots = [3]int32{0, 1, 0}

func waxwingFn6Lambda0Entry(e any) int32 {
var a0 [2]waxwingFun2
var a1 [1]int32
for p := 2; p >= 0; p-- {
switch waxwingFn6Lambda0Kinds[p] {
case 0:
v := e.(*waxwingNode1)
a0[waxwingFn6Lambda0Slots[p]] = v.value
e = v.previous
case 1:
v := e.(*waxwingNode0)
a1[waxwingFn6Lambda0Slots[p]] = v.value
e = v.previous
}
}
return waxwingFn6Lambda0(a0[0], a0[1], a1[0])
}

func main() { fmt.Println(string(waxwingShow1(nil, waxwingFn3()))) }
