// Code generated by Waxwing stage 0. DO NOT EDIT.
package main

import "fmt"

func waxwingAdd(a int32, b int32) int32 { return a + b }

func waxwingCmpBool(a bool, b bool) int { if a == b { return 0 }; if b { return -1 }; return 1 }

type waxwingTy0 struct {
tag uint32
c0f0 int32
c0f1 bool
}

func waxwingCtor0(f0 int32, f1 bool) waxwingTy0 { return waxwingTy0{tag: 1, c0f0: f0, c0f1: f1} }

type waxwingTy1 struct {
tag uint32
c2f0 *waxwingTy0
c2f1 *waxwingTy1
}

func waxwingCtor1() waxwingTy1 { return waxwingTy1{tag: 1} }

func waxwingCtor2(f0 waxwingTy0, f1 waxwingTy1) waxwingTy1 { return waxwingTy1{tag: 2, c2f0: &f0, c2f1: &f1} }

type waxwingTy2 struct {
tag uint32
c4f0 int32
}

func waxwingCtor3() waxwingTy2 { return waxwingTy2{tag: 1} }

func waxwingCtor4(f0 int32) waxwingTy2 { return waxwingTy2{tag: 2, c4f0: f0} }

type waxwingTy3 struct {
tag uint32
c5f0 *waxwingTy1
c5f1 *waxwingTy2
}

func waxwingCtor5(f0 waxwingTy1, f1 waxwingTy2) waxwingTy3 { return waxwingTy3{tag: 1, c5f0: &f0, c5f1: &f1} }

type waxwingTy4 struct {
tag uint32
c7f0 int32
c7f1 *waxwingTy4
}

func waxwingCtor6() waxwingTy4 { return waxwingTy4{tag: 1} }

func waxwingCtor7(f0 int32, f1 waxwingTy4) waxwingTy4 { return waxwingTy4{tag: 2, c7f0: f0, c7f1: &f1} }

type waxwingTy5 struct {
tag uint32
c9f0 bool
c9f1 *waxwingTy5
}

func waxwingCtor8() waxwingTy5 { return waxwingTy5{tag: 1} }

func waxwingCtor9(f0 bool, f1 waxwingTy5) waxwingTy5 { return waxwingTy5{tag: 2, c9f0: f0, c9f1: &f1} }

type waxwingTy6 struct {
tag uint32
c11f0 *waxwingTy6
c11f1 int32
c11f2 *waxwingTy6
}

func waxwingCtor10() waxwingTy6 { return waxwingTy6{tag: 1} }

func waxwingCtor11(f0 waxwingTy6, f1 int32, f2 waxwingTy6) waxwingTy6 { return waxwingTy6{tag: 2, c11f0: &f0, c11f1: f1, c11f2: &f2} }

type waxwingTy7 struct {
tag uint32
c12f0 *waxwingTy4
c12f1 *waxwingTy5
}

func waxwingCtor12(f0 waxwingTy4, f1 waxwingTy5) waxwingTy7 { return waxwingTy7{tag: 1, c12f0: &f0, c12f1: &f1} }

func waxwingCmp0(a waxwingTy0, b waxwingTy0) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c0f0 < b.c0f0 { return -1 }; if a.c0f0 > b.c0f0 { return 1 }
if c := waxwingCmpBool(a.c0f1, b.c0f1); c != 0 { return c }
}
return 0
}

func waxwingCmp1(a waxwingTy1, b waxwingTy1) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c2f0 == nil || b.c2f0 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c2f0, *b.c2f0); c != 0 { return c }
if a.c2f1 == nil || b.c2f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp1(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func waxwingCmp2(a waxwingTy2, b waxwingTy2) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c4f0 < b.c4f0 { return -1 }; if a.c4f0 > b.c4f0 { return 1 }
}
return 0
}

func waxwingCmp3(a waxwingTy3, b waxwingTy3) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c5f0 == nil || b.c5f0 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp1(*a.c5f0, *b.c5f0); c != 0 { return c }
if a.c5f1 == nil || b.c5f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp2(*a.c5f1, *b.c5f1); c != 0 { return c }
}
return 0
}

func waxwingCmp4(a waxwingTy4, b waxwingTy4) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c7f0 < b.c7f0 { return -1 }; if a.c7f0 > b.c7f0 { return 1 }
if a.c7f1 == nil || b.c7f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp4(*a.c7f1, *b.c7f1); c != 0 { return c }
}
return 0
}

func waxwingCmp5(a waxwingTy5, b waxwingTy5) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if c := waxwingCmpBool(a.c9f0, b.c9f0); c != 0 { return c }
if a.c9f1 == nil || b.c9f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp5(*a.c9f1, *b.c9f1); c != 0 { return c }
}
return 0
}

func waxwingCmp6(a waxwingTy6, b waxwingTy6) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c11f0 == nil || b.c11f0 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp6(*a.c11f0, *b.c11f0); c != 0 { return c }
if a.c11f1 < b.c11f1 { return -1 }; if a.c11f1 > b.c11f1 { return 1 }
if a.c11f2 == nil || b.c11f2 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp6(*a.c11f2, *b.c11f2); c != 0 { return c }
}
return 0
}

func waxwingCmp7(a waxwingTy7, b waxwingTy7) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c12f0 == nil || b.c12f0 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp4(*a.c12f0, *b.c12f0); c != 0 { return c }
if a.c12f1 == nil || b.c12f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp5(*a.c12f1, *b.c12f1); c != 0 { return c }
}
return 0
}

func waxwingShow0(out []byte, v waxwingTy0) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
out = fmt.Append(out, v.c0f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c0f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow1(out []byte, v waxwingTy1) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
if v.c2f0 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c2f0)
out = append(out, ", "...)
if v.c2f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow1(out, *v.c2f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow2(out []byte, v waxwingTy2) []byte {
switch v.tag {
case 1:
return append(out, "Nothing"...)
case 2:
out = append(out, "Just("...)
out = fmt.Append(out, v.c4f0)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow3(out []byte, v waxwingTy3) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
if v.c5f0 == nil { panic("waxwing: malformed value") }
out = waxwingShow1(out, *v.c5f0)
out = append(out, ", "...)
if v.c5f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow2(out, *v.c5f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow4(out []byte, v waxwingTy4) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
out = fmt.Append(out, v.c7f0)
out = append(out, ", "...)
if v.c7f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow4(out, *v.c7f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow5(out []byte, v waxwingTy5) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
out = fmt.Append(out, v.c9f0)
out = append(out, ", "...)
if v.c9f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow5(out, *v.c9f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow6(out []byte, v waxwingTy6) []byte {
switch v.tag {
case 1:
return append(out, "Leaf"...)
case 2:
out = append(out, "Node("...)
if v.c11f0 == nil { panic("waxwing: malformed value") }
out = waxwingShow6(out, *v.c11f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c11f1)
out = append(out, ", "...)
if v.c11f2 == nil { panic("waxwing: malformed value") }
out = waxwingShow6(out, *v.c11f2)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingShow7(out []byte, v waxwingTy7) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
if v.c12f0 == nil { panic("waxwing: malformed value") }
out = waxwingShow4(out, *v.c12f0)
out = append(out, ", "...)
if v.c12f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow5(out, *v.c12f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingFn0(waxwingLocal0 int32, waxwingLocal1 int32) int32 {
return func() int32 { if (waxwingLocal0 < waxwingLocal1) { return waxwingLocal1 }; return waxwingLocal0 }()
}

func waxwingFn1() waxwingTy3 {
return waxwingCtor5(waxwingFn2(waxwingFn3(waxwingCtor7(int32(1), waxwingCtor7(int32(2), waxwingCtor7(int32(3), waxwingCtor6())))), waxwingCtor9(true, waxwingCtor9(false, waxwingCtor8()))), waxwingFn4(waxwingFn5(waxwingCtor11(waxwingCtor11(waxwingCtor10(), int32(4), waxwingCtor10()), int32(5), waxwingCtor11(waxwingCtor10(), int32(6), waxwingCtor10())))))
}

func waxwingFn2(waxwingLocal0 waxwingTy4, waxwingLocal1 waxwingTy5) waxwingTy1 {
return waxwingFn2Match0(waxwingCtor12(waxwingLocal0, waxwingLocal1))
}

func waxwingFn2Match0(waxwingScrutinee waxwingTy7) waxwingTy1 {
if waxwingScrutinee.tag == 1 && waxwingScrutinee.c12f0 != nil && waxwingScrutinee.c12f0.tag == 2 && waxwingScrutinee.c12f0.c7f1 != nil && waxwingScrutinee.c12f1 != nil && waxwingScrutinee.c12f1.tag == 2 && waxwingScrutinee.c12f1.c9f1 != nil {
waxwingLocal2 := waxwingScrutinee.c12f0.c7f0
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c12f0.c7f1
_ = waxwingLocal3
waxwingLocal4 := waxwingScrutinee.c12f1.c9f0
_ = waxwingLocal4
waxwingLocal5 := *waxwingScrutinee.c12f1.c9f1
_ = waxwingLocal5
return waxwingCtor2(waxwingCtor0(waxwingLocal2, waxwingLocal4), waxwingFn2(waxwingLocal3, waxwingLocal5))
}
if true { return waxwingCtor1() }
panic("waxwing: unmatched value")
}

func waxwingFn3(waxwingLocal0 waxwingTy4) waxwingTy4 {
return waxwingFn6(waxwingLocal0, waxwingCtor6())
}

func waxwingFn4(waxwingLocal0 waxwingTy4) waxwingTy2 {
return waxwingFn4Match0(waxwingLocal0)
}

func waxwingFn4Match0(waxwingScrutinee waxwingTy4) waxwingTy2 {
if waxwingScrutinee.tag == 1 { return waxwingCtor3() }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c7f1 != nil && waxwingScrutinee.c7f1.tag == 1 {
waxwingLocal1 := waxwingScrutinee.c7f0
_ = waxwingLocal1
return waxwingCtor4(waxwingLocal1)
}
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c7f1 != nil {
waxwingLocal2 := *waxwingScrutinee.c7f1
_ = waxwingLocal2
return waxwingFn4(waxwingLocal2)
}
panic("waxwing: unmatched value")
}

func waxwingFn5(waxwingLocal0 waxwingTy6) waxwingTy4 {
return waxwingFn5Match0(waxwingLocal0)
}

func waxwingFn5Match0(waxwingScrutinee waxwingTy6) waxwingTy4 {
if waxwingScrutinee.tag == 1 { return waxwingCtor6() }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c11f0 != nil && waxwingScrutinee.c11f2 != nil {
waxwingLocal1 := *waxwingScrutinee.c11f0
_ = waxwingLocal1
waxwingLocal2 := waxwingScrutinee.c11f1
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c11f2
_ = waxwingLocal3
return waxwingFn7(waxwingFn5(waxwingLocal1), waxwingCtor7(waxwingLocal2, waxwingFn5(waxwingLocal3)))
}
panic("waxwing: unmatched value")
}

func waxwingFn6(waxwingLocal0 waxwingTy4, waxwingLocal1 waxwingTy4) waxwingTy4 {
return waxwingFn6Match0(waxwingLocal1, waxwingLocal0)
}

func waxwingFn6Match0(waxwingLocal1 waxwingTy4, waxwingScrutinee waxwingTy4) waxwingTy4 {
if waxwingScrutinee.tag == 1 { return waxwingLocal1 }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c7f1 != nil {
waxwingLocal2 := waxwingScrutinee.c7f0
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c7f1
_ = waxwingLocal3
return waxwingFn6(waxwingLocal3, waxwingCtor7(waxwingLocal2, waxwingLocal1))
}
panic("waxwing: unmatched value")
}

func waxwingFn7(waxwingLocal0 waxwingTy4, waxwingLocal1 waxwingTy4) waxwingTy4 {
return waxwingFn7Match0(waxwingLocal1, waxwingLocal0)
}

func waxwingFn7Match0(waxwingLocal1 waxwingTy4, waxwingScrutinee waxwingTy4) waxwingTy4 {
if waxwingScrutinee.tag == 1 { return waxwingLocal1 }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c7f1 != nil {
waxwingLocal2 := waxwingScrutinee.c7f0
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c7f1
_ = waxwingLocal3
return waxwingCtor7(waxwingLocal2, waxwingFn7(waxwingLocal3, waxwingLocal1))
}
panic("waxwing: unmatched value")
}

func main() { fmt.Println(string(waxwingShow3(nil, waxwingFn1()))) }
