// Code generated by Bumpus stage 0. DO NOT EDIT.
package main

import "fmt"

func bumpusAdd(a int32, b int32) int32 { return a + b }

func bumpusCmpBool(a bool, b bool) int { if a == b { return 0 }; if b { return -1 }; return 1 }

type bumpusTy0 struct {
tag uint32
c0f0 int32
c0f1 bool
}

func bumpusCtor0(f0 int32, f1 bool) bumpusTy0 { return bumpusTy0{tag: 1, c0f0: f0, c0f1: f1} }

type bumpusTy1 struct {
tag uint32
c2f0 *bumpusTy0
c2f1 *bumpusTy1
}

func bumpusCtor1() bumpusTy1 { return bumpusTy1{tag: 1} }

func bumpusCtor2(f0 bumpusTy0, f1 bumpusTy1) bumpusTy1 { return bumpusTy1{tag: 2, c2f0: &f0, c2f1: &f1} }

type bumpusTy2 struct {
tag uint32
c4f0 int32
}

func bumpusCtor3() bumpusTy2 { return bumpusTy2{tag: 1} }

func bumpusCtor4(f0 int32) bumpusTy2 { return bumpusTy2{tag: 2, c4f0: f0} }

type bumpusTy3 struct {
tag uint32
c5f0 *bumpusTy1
c5f1 *bumpusTy2
}

func bumpusCtor5(f0 bumpusTy1, f1 bumpusTy2) bumpusTy3 { return bumpusTy3{tag: 1, c5f0: &f0, c5f1: &f1} }

type bumpusTy4 struct {
tag uint32
c7f0 int32
c7f1 *bumpusTy4
}

func bumpusCtor6() bumpusTy4 { return bumpusTy4{tag: 1} }

func bumpusCtor7(f0 int32, f1 bumpusTy4) bumpusTy4 { return bumpusTy4{tag: 2, c7f0: f0, c7f1: &f1} }

type bumpusTy5 struct {
tag uint32
c9f0 bool
c9f1 *bumpusTy5
}

func bumpusCtor8() bumpusTy5 { return bumpusTy5{tag: 1} }

func bumpusCtor9(f0 bool, f1 bumpusTy5) bumpusTy5 { return bumpusTy5{tag: 2, c9f0: f0, c9f1: &f1} }

type bumpusTy6 struct {
tag uint32
c11f0 *bumpusTy6
c11f1 int32
c11f2 *bumpusTy6
}

func bumpusCtor10() bumpusTy6 { return bumpusTy6{tag: 1} }

func bumpusCtor11(f0 bumpusTy6, f1 int32, f2 bumpusTy6) bumpusTy6 { return bumpusTy6{tag: 2, c11f0: &f0, c11f1: f1, c11f2: &f2} }

type bumpusTy7 struct {
tag uint32
c12f0 *bumpusTy4
c12f1 *bumpusTy5
}

func bumpusCtor12(f0 bumpusTy4, f1 bumpusTy5) bumpusTy7 { return bumpusTy7{tag: 1, c12f0: &f0, c12f1: &f1} }

func bumpusCmp0(a bumpusTy0, b bumpusTy0) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c0f0 < b.c0f0 { return -1 }; if a.c0f0 > b.c0f0 { return 1 }
if c := bumpusCmpBool(a.c0f1, b.c0f1); c != 0 { return c }
}
return 0
}

func bumpusCmp1(a bumpusTy1, b bumpusTy1) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c2f0 == nil || b.c2f0 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c2f0, *b.c2f0); c != 0 { return c }
if a.c2f1 == nil || b.c2f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp1(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func bumpusCmp2(a bumpusTy2, b bumpusTy2) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c4f0 < b.c4f0 { return -1 }; if a.c4f0 > b.c4f0 { return 1 }
}
return 0
}

func bumpusCmp3(a bumpusTy3, b bumpusTy3) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c5f0 == nil || b.c5f0 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp1(*a.c5f0, *b.c5f0); c != 0 { return c }
if a.c5f1 == nil || b.c5f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp2(*a.c5f1, *b.c5f1); c != 0 { return c }
}
return 0
}

func bumpusCmp4(a bumpusTy4, b bumpusTy4) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c7f0 < b.c7f0 { return -1 }; if a.c7f0 > b.c7f0 { return 1 }
if a.c7f1 == nil || b.c7f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp4(*a.c7f1, *b.c7f1); c != 0 { return c }
}
return 0
}

func bumpusCmp5(a bumpusTy5, b bumpusTy5) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if c := bumpusCmpBool(a.c9f0, b.c9f0); c != 0 { return c }
if a.c9f1 == nil || b.c9f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp5(*a.c9f1, *b.c9f1); c != 0 { return c }
}
return 0
}

func bumpusCmp6(a bumpusTy6, b bumpusTy6) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c11f0 == nil || b.c11f0 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp6(*a.c11f0, *b.c11f0); c != 0 { return c }
if a.c11f1 < b.c11f1 { return -1 }; if a.c11f1 > b.c11f1 { return 1 }
if a.c11f2 == nil || b.c11f2 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp6(*a.c11f2, *b.c11f2); c != 0 { return c }
}
return 0
}

func bumpusCmp7(a bumpusTy7, b bumpusTy7) int {
if a.tag < 1 || a.tag > 1 || b.tag < 1 || b.tag > 1 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 1 {
if a.c12f0 == nil || b.c12f0 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp4(*a.c12f0, *b.c12f0); c != 0 { return c }
if a.c12f1 == nil || b.c12f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp5(*a.c12f1, *b.c12f1); c != 0 { return c }
}
return 0
}

func bumpusShow0(out []byte, v bumpusTy0) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
out = fmt.Append(out, v.c0f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c0f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow1(out []byte, v bumpusTy1) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
if v.c2f0 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c2f0)
out = append(out, ", "...)
if v.c2f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow1(out, *v.c2f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow2(out []byte, v bumpusTy2) []byte {
switch v.tag {
case 1:
return append(out, "Nothing"...)
case 2:
out = append(out, "Just("...)
out = fmt.Append(out, v.c4f0)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow3(out []byte, v bumpusTy3) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
if v.c5f0 == nil { panic("bumpus: malformed value") }
out = bumpusShow1(out, *v.c5f0)
out = append(out, ", "...)
if v.c5f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow2(out, *v.c5f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow4(out []byte, v bumpusTy4) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
out = fmt.Append(out, v.c7f0)
out = append(out, ", "...)
if v.c7f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow4(out, *v.c7f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow5(out []byte, v bumpusTy5) []byte {
switch v.tag {
case 1:
return append(out, "Nil"...)
case 2:
out = append(out, "Cons("...)
out = fmt.Append(out, v.c9f0)
out = append(out, ", "...)
if v.c9f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow5(out, *v.c9f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow6(out []byte, v bumpusTy6) []byte {
switch v.tag {
case 1:
return append(out, "Leaf"...)
case 2:
out = append(out, "Node("...)
if v.c11f0 == nil { panic("bumpus: malformed value") }
out = bumpusShow6(out, *v.c11f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c11f1)
out = append(out, ", "...)
if v.c11f2 == nil { panic("bumpus: malformed value") }
out = bumpusShow6(out, *v.c11f2)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusShow7(out []byte, v bumpusTy7) []byte {
switch v.tag {
case 1:
out = append(out, "Pair("...)
if v.c12f0 == nil { panic("bumpus: malformed value") }
out = bumpusShow4(out, *v.c12f0)
out = append(out, ", "...)
if v.c12f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow5(out, *v.c12f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusFn0(bumpusLocal0 int32, bumpusLocal1 int32) int32 {
return func() int32 { if (bumpusLocal0 < bumpusLocal1) { return bumpusLocal1 }; return bumpusLocal0 }()
}

func bumpusFn1() bumpusTy3 {
return bumpusCtor5(bumpusFn2(bumpusFn3(bumpusCtor7(int32(1), bumpusCtor7(int32(2), bumpusCtor7(int32(3), bumpusCtor6())))), bumpusCtor9(true, bumpusCtor9(false, bumpusCtor8()))), bumpusFn4(bumpusFn5(bumpusCtor11(bumpusCtor11(bumpusCtor10(), int32(4), bumpusCtor10()), int32(5), bumpusCtor11(bumpusCtor10(), int32(6), bumpusCtor10())))))
}

func bumpusFn2(bumpusLocal0 bumpusTy4, bumpusLocal1 bumpusTy5) bumpusTy1 {
return bumpusFn2Match0(bumpusCtor12(bumpusLocal0, bumpusLocal1))
}

func bumpusFn2Match0(bumpusScrutinee bumpusTy7) bumpusTy1 {
if bumpusScrutinee.tag == 1 && bumpusScrutinee.c12f0 != nil && bumpusScrutinee.c12f0.tag == 2 && bumpusScrutinee.c12f0.c7f1 != nil && bumpusScrutinee.c12f1 != nil && bumpusScrutinee.c12f1.tag == 2 && bumpusScrutinee.c12f1.c9f1 != nil {
bumpusLocal2 := bumpusScrutinee.c12f0.c7f0
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c12f0.c7f1
_ = bumpusLocal3
bumpusLocal4 := bumpusScrutinee.c12f1.c9f0
_ = bumpusLocal4
bumpusLocal5 := *bumpusScrutinee.c12f1.c9f1
_ = bumpusLocal5
return bumpusCtor2(bumpusCtor0(bumpusLocal2, bumpusLocal4), bumpusFn2(bumpusLocal3, bumpusLocal5))
}
if true { return bumpusCtor1() }
panic("bumpus: unmatched value")
}

func bumpusFn3(bumpusLocal0 bumpusTy4) bumpusTy4 {
return bumpusFn6(bumpusLocal0, bumpusCtor6())
}

func bumpusFn4(bumpusLocal0 bumpusTy4) bumpusTy2 {
return bumpusFn4Match0(bumpusLocal0)
}

func bumpusFn4Match0(bumpusScrutinee bumpusTy4) bumpusTy2 {
if bumpusScrutinee.tag == 1 { return bumpusCtor3() }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c7f1 != nil && bumpusScrutinee.c7f1.tag == 1 {
bumpusLocal1 := bumpusScrutinee.c7f0
_ = bumpusLocal1
return bumpusCtor4(bumpusLocal1)
}
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c7f1 != nil {
bumpusLocal2 := *bumpusScrutinee.c7f1
_ = bumpusLocal2
return bumpusFn4(bumpusLocal2)
}
panic("bumpus: unmatched value")
}

func bumpusFn5(bumpusLocal0 bumpusTy6) bumpusTy4 {
return bumpusFn5Match0(bumpusLocal0)
}

func bumpusFn5Match0(bumpusScrutinee bumpusTy6) bumpusTy4 {
if bumpusScrutinee.tag == 1 { return bumpusCtor6() }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c11f0 != nil && bumpusScrutinee.c11f2 != nil {
bumpusLocal1 := *bumpusScrutinee.c11f0
_ = bumpusLocal1
bumpusLocal2 := bumpusScrutinee.c11f1
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c11f2
_ = bumpusLocal3
return bumpusFn7(bumpusFn5(bumpusLocal1), bumpusCtor7(bumpusLocal2, bumpusFn5(bumpusLocal3)))
}
panic("bumpus: unmatched value")
}

func bumpusFn6(bumpusLocal0 bumpusTy4, bumpusLocal1 bumpusTy4) bumpusTy4 {
return bumpusFn6Match0(bumpusLocal1, bumpusLocal0)
}

func bumpusFn6Match0(bumpusLocal1 bumpusTy4, bumpusScrutinee bumpusTy4) bumpusTy4 {
if bumpusScrutinee.tag == 1 { return bumpusLocal1 }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c7f1 != nil {
bumpusLocal2 := bumpusScrutinee.c7f0
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c7f1
_ = bumpusLocal3
return bumpusFn6(bumpusLocal3, bumpusCtor7(bumpusLocal2, bumpusLocal1))
}
panic("bumpus: unmatched value")
}

func bumpusFn7(bumpusLocal0 bumpusTy4, bumpusLocal1 bumpusTy4) bumpusTy4 {
return bumpusFn7Match0(bumpusLocal1, bumpusLocal0)
}

func bumpusFn7Match0(bumpusLocal1 bumpusTy4, bumpusScrutinee bumpusTy4) bumpusTy4 {
if bumpusScrutinee.tag == 1 { return bumpusLocal1 }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c7f1 != nil {
bumpusLocal2 := bumpusScrutinee.c7f0
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c7f1
_ = bumpusLocal3
return bumpusCtor7(bumpusLocal2, bumpusFn7(bumpusLocal3, bumpusLocal1))
}
panic("bumpus: unmatched value")
}

func main() { fmt.Println(string(bumpusShow3(nil, bumpusFn1()))) }
