// Code generated by Sprig stage 0. DO NOT EDIT.
package main

import "fmt"

func sprigAdd(a int32, b int32) int32 { return a + b }

type sprigTy0 struct {
tag uint32
c1f0 int32
c2f0 *sprigTy0
c2f1 *sprigTy0
}

func sprigCtor0() sprigTy0 { return sprigTy0{tag: 1} }

func sprigCtor1(f0 int32) sprigTy0 { return sprigTy0{tag: 2, c1f0: f0} }

func sprigCtor2(f0 sprigTy0, f1 sprigTy0) sprigTy0 { return sprigTy0{tag: 3, c2f0: &f0, c2f1: &f1} }

func sprigCmp0(a sprigTy0, b sprigTy0) int {
if a.tag < 1 || a.tag > 3 || b.tag < 1 || b.tag > 3 { panic("sprig: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 < b.c1f0 { return -1 }; if a.c1f0 > b.c1f0 { return 1 }
}
if a.tag == 3 {
if a.c2f0 == nil || b.c2f0 == nil { panic("sprig: malformed value") }
if c := sprigCmp0(*a.c2f0, *b.c2f0); c != 0 { return c }
if a.c2f1 == nil || b.c2f1 == nil { panic("sprig: malformed value") }
if c := sprigCmp0(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func sprigFn0(sprigLocal0 sprigTy0) int32 {
return func(sprigMatch0 sprigTy0) int32 {
if sprigMatch0.tag == 1 { return int32(1) }
if sprigMatch0.tag == 2 {
sprigLocal1 := sprigMatch0.c1f0
_ = sprigLocal1
return sprigAdd(sprigAdd(sprigAdd(sprigLocal1, sprigLocal1), sprigLocal1), sprigLocal1)
}
if sprigMatch0.tag == 3 && sprigMatch0.c2f0 != nil && sprigMatch0.c2f0.tag == 1 && sprigMatch0.c2f1 != nil && sprigMatch0.c2f1.tag == 1 { return int32(2) }
if sprigMatch0.tag == 3 && sprigMatch0.c2f0 != nil && sprigMatch0.c2f1 != nil {
sprigLocal2 := *sprigMatch0.c2f0
_ = sprigLocal2
sprigLocal3 := *sprigMatch0.c2f1
_ = sprigLocal3
return func(sprigMatch1 sprigTy0) int32 {
if sprigMatch1.tag == 1 { return sprigAdd(int32(100), sprigFn0(sprigLocal3)) }
if true { return sprigAdd(sprigFn0(sprigLocal2), sprigFn0(sprigLocal3)) }
panic("sprig: unmatched value")
}(sprigLocal2)
}
panic("sprig: unmatched value")
}(sprigLocal0)
}

func sprigFn1() int32 {
return sprigFn0(sprigCtor2(sprigCtor1(int32(3)), sprigCtor2(sprigCtor0(), sprigCtor1(int32(2)))))
}

func main() { fmt.Println(sprigFn1()) }
