// Code generated by Waxwing stage 0. DO NOT EDIT.
package main

import "fmt"

func waxwingAdd(a int32, b int32) int32 { return a + b }

type waxwingTy0 struct {
tag uint32
c1f0 int32
c2f0 *waxwingTy0
c2f1 *waxwingTy0
}

func waxwingCtor0() waxwingTy0 { return waxwingTy0{tag: 1} }

func waxwingCtor1(f0 int32) waxwingTy0 { return waxwingTy0{tag: 2, c1f0: f0} }

func waxwingCtor2(f0 waxwingTy0, f1 waxwingTy0) waxwingTy0 { return waxwingTy0{tag: 3, c2f0: &f0, c2f1: &f1} }

func waxwingCmp0(a waxwingTy0, b waxwingTy0) int {
if a.tag < 1 || a.tag > 3 || b.tag < 1 || b.tag > 3 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 < b.c1f0 { return -1 }; if a.c1f0 > b.c1f0 { return 1 }
}
if a.tag == 3 {
if a.c2f0 == nil || b.c2f0 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c2f0, *b.c2f0); c != 0 { return c }
if a.c2f1 == nil || b.c2f1 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func waxwingShow0(out []byte, v waxwingTy0) []byte {
switch v.tag {
case 1:
return append(out, "Dot"...)
case 2:
out = append(out, "Square("...)
out = fmt.Append(out, v.c1f0)
return append(out, ')')
case 3:
out = append(out, "Pair("...)
if v.c2f0 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c2f0)
out = append(out, ", "...)
if v.c2f1 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c2f1)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingFn0(waxwingLocal0 waxwingTy0) int32 {
return waxwingFn0Match0(waxwingLocal0)
}

func waxwingFn0Match0(waxwingScrutinee waxwingTy0) int32 {
if waxwingScrutinee.tag == 1 { return int32(1) }
if waxwingScrutinee.tag == 2 {
waxwingLocal1 := waxwingScrutinee.c1f0
_ = waxwingLocal1
return waxwingAdd(waxwingAdd(waxwingAdd(waxwingLocal1, waxwingLocal1), waxwingLocal1), waxwingLocal1)
}
if waxwingScrutinee.tag == 3 && waxwingScrutinee.c2f0 != nil && waxwingScrutinee.c2f0.tag == 1 && waxwingScrutinee.c2f1 != nil && waxwingScrutinee.c2f1.tag == 1 { return int32(2) }
if waxwingScrutinee.tag == 3 && waxwingScrutinee.c2f0 != nil && waxwingScrutinee.c2f1 != nil {
waxwingLocal2 := *waxwingScrutinee.c2f0
_ = waxwingLocal2
waxwingLocal3 := *waxwingScrutinee.c2f1
_ = waxwingLocal3
return waxwingFn0Match1(waxwingLocal2, waxwingLocal3, waxwingLocal2)
}
panic("waxwing: unmatched value")
}

func waxwingFn0Match1(waxwingLocal2 waxwingTy0, waxwingLocal3 waxwingTy0, waxwingScrutinee waxwingTy0) int32 {
if waxwingScrutinee.tag == 1 { return waxwingAdd(int32(100), waxwingFn0(waxwingLocal3)) }
if true { return waxwingAdd(waxwingFn0(waxwingLocal2), waxwingFn0(waxwingLocal3)) }
panic("waxwing: unmatched value")
}

func waxwingFn1() int32 {
return waxwingFn0(waxwingCtor2(waxwingCtor1(int32(3)), waxwingCtor2(waxwingCtor0(), waxwingCtor1(int32(2)))))
}

func main() { fmt.Println(waxwingFn1()) }
