// Code generated by Bumpus stage 0. DO NOT EDIT.
package main

import "fmt"

func bumpusAdd(a int32, b int32) int32 { return a + b }

type bumpusTy0 struct {
tag uint32
c1f0 int32
c2f0 *bumpusTy0
c2f1 *bumpusTy0
}

func bumpusCtor0() bumpusTy0 { return bumpusTy0{tag: 1} }

func bumpusCtor1(f0 int32) bumpusTy0 { return bumpusTy0{tag: 2, c1f0: f0} }

func bumpusCtor2(f0 bumpusTy0, f1 bumpusTy0) bumpusTy0 { return bumpusTy0{tag: 3, c2f0: &f0, c2f1: &f1} }

func bumpusCmp0(a bumpusTy0, b bumpusTy0) int {
if a.tag < 1 || a.tag > 3 || b.tag < 1 || b.tag > 3 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 < b.c1f0 { return -1 }; if a.c1f0 > b.c1f0 { return 1 }
}
if a.tag == 3 {
if a.c2f0 == nil || b.c2f0 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c2f0, *b.c2f0); c != 0 { return c }
if a.c2f1 == nil || b.c2f1 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c2f1, *b.c2f1); c != 0 { return c }
}
return 0
}

func bumpusShow0(out []byte, v bumpusTy0) []byte {
switch v.tag {
case 1:
return append(out, "Dot"...)
case 2:
out = append(out, "Square("...)
out = fmt.Append(out, v.c1f0)
return append(out, ')')
case 3:
out = append(out, "Pair("...)
if v.c2f0 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c2f0)
out = append(out, ", "...)
if v.c2f1 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c2f1)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusFn0(bumpusLocal0 bumpusTy0) int32 {
return bumpusFn0Match0(bumpusLocal0)
}

func bumpusFn0Match0(bumpusScrutinee bumpusTy0) int32 {
if bumpusScrutinee.tag == 1 { return int32(1) }
if bumpusScrutinee.tag == 2 {
bumpusLocal1 := bumpusScrutinee.c1f0
_ = bumpusLocal1
return bumpusAdd(bumpusAdd(bumpusAdd(bumpusLocal1, bumpusLocal1), bumpusLocal1), bumpusLocal1)
}
if bumpusScrutinee.tag == 3 && bumpusScrutinee.c2f0 != nil && bumpusScrutinee.c2f0.tag == 1 && bumpusScrutinee.c2f1 != nil && bumpusScrutinee.c2f1.tag == 1 { return int32(2) }
if bumpusScrutinee.tag == 3 && bumpusScrutinee.c2f0 != nil && bumpusScrutinee.c2f1 != nil {
bumpusLocal2 := *bumpusScrutinee.c2f0
_ = bumpusLocal2
bumpusLocal3 := *bumpusScrutinee.c2f1
_ = bumpusLocal3
return bumpusFn0Match1(bumpusLocal2, bumpusLocal3, bumpusLocal2)
}
panic("bumpus: unmatched value")
}

func bumpusFn0Match1(bumpusLocal2 bumpusTy0, bumpusLocal3 bumpusTy0, bumpusScrutinee bumpusTy0) int32 {
if bumpusScrutinee.tag == 1 { return bumpusAdd(int32(100), bumpusFn0(bumpusLocal3)) }
if true { return bumpusAdd(bumpusFn0(bumpusLocal2), bumpusFn0(bumpusLocal3)) }
panic("bumpus: unmatched value")
}

func bumpusFn1() int32 {
return bumpusFn0(bumpusCtor2(bumpusCtor1(int32(3)), bumpusCtor2(bumpusCtor0(), bumpusCtor1(int32(2)))))
}

func main() { fmt.Println(bumpusFn1()) }
