// Code generated by Waxwing stage 0. DO NOT EDIT.
package main

import "fmt"

func waxwingAdd(a int32, b int32) int32 { return a + b }

type waxwingTy0 struct {
tag uint32
c1f0 *waxwingTy0
c1f1 int32
c1f2 *waxwingTy0
}

func waxwingCtor0() waxwingTy0 { return waxwingTy0{tag: 1} }

func waxwingCtor1(f0 waxwingTy0, f1 int32, f2 waxwingTy0) waxwingTy0 { return waxwingTy0{tag: 2, c1f0: &f0, c1f1: f1, c1f2: &f2} }

func waxwingCmp0(a waxwingTy0, b waxwingTy0) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("waxwing: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 == nil || b.c1f0 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c1f0, *b.c1f0); c != 0 { return c }
if a.c1f1 < b.c1f1 { return -1 }; if a.c1f1 > b.c1f1 { return 1 }
if a.c1f2 == nil || b.c1f2 == nil { panic("waxwing: malformed value") }
if c := waxwingCmp0(*a.c1f2, *b.c1f2); c != 0 { return c }
}
return 0
}

func waxwingShow0(out []byte, v waxwingTy0) []byte {
switch v.tag {
case 1:
return append(out, "Leaf"...)
case 2:
out = append(out, "Node("...)
if v.c1f0 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c1f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c1f1)
out = append(out, ", "...)
if v.c1f2 == nil { panic("waxwing: malformed value") }
out = waxwingShow0(out, *v.c1f2)
return append(out, ')')
}
panic("waxwing: malformed value")
}

func waxwingFn0(waxwingLocal0 waxwingTy0, waxwingLocal1 int32) waxwingTy0 {
return waxwingFn0Match0(waxwingLocal0, waxwingLocal1, waxwingLocal0)
}

func waxwingFn0Match0(waxwingLocal0 waxwingTy0, waxwingLocal1 int32, waxwingScrutinee waxwingTy0) waxwingTy0 {
if waxwingScrutinee.tag == 1 { return waxwingCtor1(waxwingCtor0(), waxwingLocal1, waxwingCtor0()) }
if waxwingScrutinee.tag == 2 && waxwingScrutinee.c1f0 != nil && waxwingScrutinee.c1f2 != nil {
waxwingLocal2 := *waxwingScrutinee.c1f0
_ = waxwingLocal2
waxwingLocal3 := waxwingScrutinee.c1f1
_ = waxwingLocal3
waxwingLocal4 := *waxwingScrutinee.c1f2
_ = waxwingLocal4
return func() waxwingTy0 { if (waxwingLocal1 < waxwingLocal3) { return waxwingCtor1(waxwingFn0(waxwingLocal2, waxwingLocal1), waxwingLocal3, waxwingLocal4) }; return func() waxwingTy0 { if (waxwingLocal1 == waxwingLocal3) { return waxwingLocal0 }; return waxwingCtor1(waxwingLocal2, waxwingLocal3, waxwingFn0(waxwingLocal4, waxwingLocal1)) }() }()
}
panic("waxwing: unmatched value")
}

func waxwingFn1() waxwingTy0 {
return waxwingFn0(waxwingFn0(waxwingFn0(waxwingFn0(waxwingFn0(waxwingCtor0(), int32(5)), int32(3)), int32(8)), int32(3)), int32(1))
}

func main() { fmt.Println(string(waxwingShow0(nil, waxwingFn1()))) }
