// Code generated by Sprig stage 0. DO NOT EDIT.
package main

import "fmt"

func sprigAdd(a int32, b int32) int32 { return a + b }

type sprigTy0 struct {
tag uint32
c1f0 *sprigTy0
c1f1 int32
c1f2 *sprigTy0
}

func sprigCtor0() sprigTy0 { return sprigTy0{tag: 1} }

func sprigCtor1(f0 sprigTy0, f1 int32, f2 sprigTy0) sprigTy0 { return sprigTy0{tag: 2, c1f0: &f0, c1f1: f1, c1f2: &f2} }

func sprigCmp0(a sprigTy0, b sprigTy0) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("sprig: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 == nil || b.c1f0 == nil { panic("sprig: malformed value") }
if c := sprigCmp0(*a.c1f0, *b.c1f0); c != 0 { return c }
if a.c1f1 < b.c1f1 { return -1 }; if a.c1f1 > b.c1f1 { return 1 }
if a.c1f2 == nil || b.c1f2 == nil { panic("sprig: malformed value") }
if c := sprigCmp0(*a.c1f2, *b.c1f2); c != 0 { return c }
}
return 0
}

func sprigShow0(out []byte, v sprigTy0) []byte {
switch v.tag {
case 1:
return append(out, "Leaf"...)
case 2:
out = append(out, "Node("...)
if v.c1f0 == nil { panic("sprig: malformed value") }
out = sprigShow0(out, *v.c1f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c1f1)
out = append(out, ", "...)
if v.c1f2 == nil { panic("sprig: malformed value") }
out = sprigShow0(out, *v.c1f2)
return append(out, ')')
}
panic("sprig: malformed value")
}

func sprigFn0(sprigLocal0 sprigTy0, sprigLocal1 int32) sprigTy0 {
return func(sprigMatch0 sprigTy0) sprigTy0 {
if sprigMatch0.tag == 1 { return sprigCtor1(sprigCtor0(), sprigLocal1, sprigCtor0()) }
if sprigMatch0.tag == 2 && sprigMatch0.c1f0 != nil && sprigMatch0.c1f2 != nil {
sprigLocal2 := *sprigMatch0.c1f0
_ = sprigLocal2
sprigLocal3 := sprigMatch0.c1f1
_ = sprigLocal3
sprigLocal4 := *sprigMatch0.c1f2
_ = sprigLocal4
return func() sprigTy0 { if (sprigLocal1 < sprigLocal3) { return sprigCtor1(sprigFn0(sprigLocal2, sprigLocal1), sprigLocal3, sprigLocal4) }; return func() sprigTy0 { if (sprigLocal1 == sprigLocal3) { return sprigLocal0 }; return sprigCtor1(sprigLocal2, sprigLocal3, sprigFn0(sprigLocal4, sprigLocal1)) }() }()
}
panic("sprig: unmatched value")
}(sprigLocal0)
}

func sprigFn1() sprigTy0 {
return sprigFn0(sprigFn0(sprigFn0(sprigFn0(sprigFn0(sprigCtor0(), int32(5)), int32(3)), int32(8)), int32(3)), int32(1))
}

func main() { fmt.Println(string(sprigShow0(nil, sprigFn1()))) }
