// Code generated by Bumpus stage 0. DO NOT EDIT.
package main

import "fmt"

func bumpusAdd(a int32, b int32) int32 { return a + b }

type bumpusTy0 struct {
tag uint32
c1f0 *bumpusTy0
c1f1 int32
c1f2 *bumpusTy0
}

func bumpusCtor0() bumpusTy0 { return bumpusTy0{tag: 1} }

func bumpusCtor1(f0 bumpusTy0, f1 int32, f2 bumpusTy0) bumpusTy0 { return bumpusTy0{tag: 2, c1f0: &f0, c1f1: f1, c1f2: &f2} }

func bumpusCmp0(a bumpusTy0, b bumpusTy0) int {
if a.tag < 1 || a.tag > 2 || b.tag < 1 || b.tag > 2 { panic("bumpus: malformed value") }
if a.tag != b.tag { if a.tag < b.tag { return -1 }; return 1 }
if a.tag == 2 {
if a.c1f0 == nil || b.c1f0 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c1f0, *b.c1f0); c != 0 { return c }
if a.c1f1 < b.c1f1 { return -1 }; if a.c1f1 > b.c1f1 { return 1 }
if a.c1f2 == nil || b.c1f2 == nil { panic("bumpus: malformed value") }
if c := bumpusCmp0(*a.c1f2, *b.c1f2); c != 0 { return c }
}
return 0
}

func bumpusShow0(out []byte, v bumpusTy0) []byte {
switch v.tag {
case 1:
return append(out, "Leaf"...)
case 2:
out = append(out, "Node("...)
if v.c1f0 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c1f0)
out = append(out, ", "...)
out = fmt.Append(out, v.c1f1)
out = append(out, ", "...)
if v.c1f2 == nil { panic("bumpus: malformed value") }
out = bumpusShow0(out, *v.c1f2)
return append(out, ')')
}
panic("bumpus: malformed value")
}

func bumpusFn0(bumpusLocal0 bumpusTy0, bumpusLocal1 int32) bumpusTy0 {
return bumpusFn0Match0(bumpusLocal0, bumpusLocal1, bumpusLocal0)
}

func bumpusFn0Match0(bumpusLocal0 bumpusTy0, bumpusLocal1 int32, bumpusScrutinee bumpusTy0) bumpusTy0 {
if bumpusScrutinee.tag == 1 { return bumpusCtor1(bumpusCtor0(), bumpusLocal1, bumpusCtor0()) }
if bumpusScrutinee.tag == 2 && bumpusScrutinee.c1f0 != nil && bumpusScrutinee.c1f2 != nil {
bumpusLocal2 := *bumpusScrutinee.c1f0
_ = bumpusLocal2
bumpusLocal3 := bumpusScrutinee.c1f1
_ = bumpusLocal3
bumpusLocal4 := *bumpusScrutinee.c1f2
_ = bumpusLocal4
return func() bumpusTy0 { if (bumpusLocal1 < bumpusLocal3) { return bumpusCtor1(bumpusFn0(bumpusLocal2, bumpusLocal1), bumpusLocal3, bumpusLocal4) }; return func() bumpusTy0 { if (bumpusLocal1 == bumpusLocal3) { return bumpusLocal0 }; return bumpusCtor1(bumpusLocal2, bumpusLocal3, bumpusFn0(bumpusLocal4, bumpusLocal1)) }() }()
}
panic("bumpus: unmatched value")
}

func bumpusFn1() bumpusTy0 {
return bumpusFn0(bumpusFn0(bumpusFn0(bumpusFn0(bumpusFn0(bumpusCtor0(), int32(5)), int32(3)), int32(8)), int32(3)), int32(1))
}

func main() { fmt.Println(string(bumpusShow0(nil, bumpusFn1()))) }
