module Sprig.Go (emit) where

import Prelude
import Data.Array as Array
import Data.String.Common (joinWith)
import Sprig.Check (CheckedProgram)
import Sprig.IR.Internal as IR
import Sprig.Model (Ty(..))
import Sprig.Resolved (FunctionId(..), LocalId(..))

emit ∷ CheckedProgram → String
emit (IR.Program program) =
  "// Code generated by Sprig stage 0. DO NOT EDIT.\n"
    <> "package main\n\nimport \"fmt\"\n\n"
    <> "func sprigAdd(a int32, b int32) int32 { return a + b }\n\n"
    <> joinWith "\n" (map function program.functions)
    <> "\nfunc main() { fmt.Println("
    <> functionName program.entry
    <> "()) }\n"

function ∷ IR.FunctionDecl → String
function definition =
  "func " <> functionName definition.id <> "(" <> joinWith ", " parameters
    <> ") "
    <> goType definition.result
    <> " {\nreturn "
    <> expression definition.body
    <> "\n}\n"
  where
  parameters = Array.mapWithIndex parameter definition.parameters
  parameter index ty = localName (LocalId index) <> " " <> goType ty

expression ∷ IR.Expr → String
expression (IR.Expr term) = case term.node of
  IR.Integer value → "int32(" <> show value <> ")"
  IR.Boolean value → if value then "true" else "false"
  IR.Local id → localName id
  IR.Call id arguments → functionName id <> "("
    <> joinWith ", " (map expression arguments)
    <> ")"
  IR.Add left right → "sprigAdd(" <> expression left <> ", " <> expression right
    <> ")"
  IR.If condition yes no → "func() " <> goType term.ty <> " { if "
    <> expression condition
    <> " { return "
    <> expression yes
    <> " }; return "
    <> expression no
    <> " }()"

goType ∷ Ty → String
goType TInt = "int32"
goType TBool = "bool"

functionName ∷ FunctionId → String
functionName (FunctionId index) = "sprigFn" <> show index

localName ∷ LocalId → String
localName (LocalId index) = "sprigLocal" <> show index
