module Sprig.Go (emit) where

import Prelude
import Data.Array as Array
import Data.String.Common (joinWith)
import Sprig.Check (CheckedProgram)
import Sprig.IR.Internal as IR
import Sprig.Go.Data (ctorName, declarations, goType)
import Sprig.Resolved (FunctionId(..), LocalId(..), Ty)

emit ∷ CheckedProgram → String
emit (IR.Program program) =
  "// Code generated by Sprig stage 0. DO NOT EDIT.\n"
    <> "package main\n\nimport \"fmt\"\n\n"
    <> "func sprigAdd(a int32, b int32) int32 { return a + b }\n\n"
    <> declarations program.types program.ctors
    <> joinWith "\n" (map emitFunction program.functions)
    <> "\nfunc main() { fmt.Println("
    <> functionName program.entry
    <> "()) }\n"
  where
  emitFunction = function

function ∷ IR.FunctionDecl → String
function definition =
  "func " <> functionName definition.id <> "(" <> joinWith ", " parameters
    <> ") "
    <> goType definition.result
    <> " {\nreturn "
    <> expression definition.body
    <> "\n}\n"
  where
  parameters = Array.mapWithIndex parameter definition.parameters
  parameter index ty = localName (LocalId index) <> " " <> goType ty

expression ∷ IR.Expr → String
expression (IR.Expr term) = case term.node of
  IR.Integer value → integer value
  IR.Boolean value → boolean value
  IR.Local id → localName id
  IR.Call id arguments → invoke (functionName id) arguments
  IR.Construct id arguments → invoke (ctorName id) arguments
  IR.Add left right → addition left right
  IR.If condition yes no → conditional term.ty condition yes no

integer ∷ Int → String
integer value = "int32(" <> show value <> ")"

boolean ∷ Boolean → String
boolean value = if value then "true" else "false"

invoke ∷ String → Array IR.Expr → String
invoke name arguments = name <> "("
  <> joinWith ", " (map emitArgument arguments)
  <> ")"
  where
  emitArgument = expression

addition ∷ IR.Expr → IR.Expr → String
addition left right = "sprigAdd(" <> expression left <> ", " <> expression right
  <> ")"

conditional ∷ Ty → IR.Expr → IR.Expr → IR.Expr → String
conditional ty condition yes no = "func() " <> goType ty <> " { if "
  <> expression condition
  <> " { return "
  <> expression yes
  <> " }; return "
  <> expression no
  <> " }()"

functionName ∷ FunctionId → String
functionName (FunctionId index) = "sprigFn" <> show index

localName ∷ LocalId → String
localName (LocalId index) = "sprigLocal" <> show index
