import assert from 'node:assert/strict';
import { cpSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
const root = '.build/regression';
const commandTimeoutMs = 60_000;
rmSync(root, { recursive: true, force: true });
mkdirSync(root, { recursive: true });
cpSync('src', `${root}/src`, { recursive: true });
const file = `${root}/src/Sprig/Check.purs`;
const original = readFileSync(file, 'utf8');
const needle = 'require env (IR.typeOf first) second';
assert.equal(original.split(needle).length, 2, 'mutation must have exactly one target');
writeFileSync(file, original.replace(needle, 'require env (IR.typeOf second) second'));
const run = (command, args) => spawnSync(command, args, { encoding: 'utf8', timeout: commandTimeoutMs });
const built = run('purs', ['compile', `${root}/src/**/*.purs`, '.spago/p/*/src/**/*.purs', '--output', `${root}/output`]);
assert.ifError(built.error);
assert.equal(built.status, 0, built.stderr);
const healthy = run('node', ['test/regression.mjs', 'output/Sprig.Compiler/index.js', 'output']);
assert.ifError(healthy.error);
assert.equal(healthy.status, 0, healthy.stderr);
const broken = run('node', ['test/regression.mjs', `${root}/output/Sprig.Compiler/index.js`, `${root}/output`]);
assert.ifError(broken.error);
assert.equal(broken.status, 1);
assert.match(broken.stderr, /branch type mismatch was accepted/);
console.log('Regression proof: fixed compiler passes; restored branch-check defect fails.');
